import type { Warehouse } from '../../../../types';
import type { SortField } from '../types';

export const filterWarehouses = (warehouses: Warehouse[], query: string): Warehouse[] => {
  if (!query.trim()) return warehouses;
  const q = query.toLowerCase();
  return warehouses.filter(
    (w) =>
      w.name.toLowerCase().includes(q) ||
      w.code.toLowerCase().includes(q) ||
      w.province.toLowerCase().includes(q) ||
      (w.district && w.district.toLowerCase().includes(q)) ||
      (w.address && w.address.toLowerCase().includes(q)) ||
      (w.supportedProvinces && w.supportedProvinces.some((p) => p.toLowerCase().includes(q))),
  );
};

export const sortWarehouses = (
  warehouses: Warehouse[],
  field: SortField,
  asc: boolean,
): Warehouse[] => {
  return [...warehouses].sort((a, b) => {
    let valA = (a[field] || '').toString().toLowerCase();
    let valB = (b[field] || '').toString().toLowerCase();
    if (valA < valB) return asc ? -1 : 1;
    if (valA > valB) return asc ? 1 : -1;
    return 0;
  });
};

/**
 * Normalize Vietnamese text: remove diacritics, lowercase, keep alphanumeric.
 */
const normalizeText = (text: string): string => {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim();
};

/**
 * Extract acronym from a string (up to 5 chars).
 */
const getAcronym = (text: string, maxLen = 5): string => {
  const cleaned = normalizeText(text);
  if (!cleaned) return 'WH';

  const words = cleaned.split(/\s+/).filter(Boolean);

  if (words.length === 1) {
    return words[0].substring(0, maxLen).toUpperCase();
  }

  const acronym = words.map((w) => w[0]).join('').toUpperCase();
  if (acronym.length >= 2) {
    return acronym.substring(0, maxLen);
  }

  return words[0].substring(0, maxLen).toUpperCase();
};

/**
 * Generate a random 3-digit number (100-999).
 */
export const randomDigits = (): string => {
  return String(Math.floor(100 + Math.random() * 900));
};

/**
 * Generate a warehouse code from name and province.
 * Format: WH-{PROVINCE_ACRONYM}-{NAME_ACRONYM}-{3_DIGITS}
 */
export const generateWarehouseCode = (name: string, province: string, fixedSuffix?: string): string => {
  const provinceCode = getAcronym(province, 4) || 'XX';
  const nameCode = getAcronym(name, 5) || 'WH';
  const suffix = fixedSuffix || randomDigits();
  return `WH-${provinceCode}-${nameCode}-${suffix}`;
};

/**
 * Extract trailing digits from a warehouse code.
 */
export const extractCodeSuffix = (existingCode: string): string | undefined => {
  const match = existingCode.match(/(\d+)$/);
  return match ? match[1] : undefined;
};

/**
 * Regenerate just the random suffix part of an existing code.
 */
export const regenerateCodeSuffix = (existingCode: string): string => {
  const match = existingCode.match(/^(WH-[A-Z0-9]+-[A-Z0-9]+-)\d+$/);
  if (match) {
    return match[1] + randomDigits();
  }
  return existingCode;
};

/**
 * Check if a warehouse code was auto-generated.
 */
export const isAutoGeneratedCode = (code: string): boolean => {
  return /^WH-[A-Z0-9]{1,4}-[A-Z0-9]{1,5}-\d{3}$/.test(code);
};
