/**
 * Utility functions for generating auto warehouse codes.
 * Format: WH-{PROVINCE_ACRONYM}-{NAME_ACRONYM}-{RANDOM_3_DIGITS}
 * 
 * Examples:
 * - "Kho Tổng TP. Hồ Chí Minh" + "Hồ Chí Minh" → "WH-HCM-KT-429"
 * - "Hà Nội Main Warehouse" + "Hà Nội" → "WH-HN-HNMW-718"
 * - "Đà Nẵng Logistics Center" + "Đà Nẵng" → "WH-DN-DLC-153"
 * 
 * Performance: Pure functions, no side effects, memoizable.
 */

/**
 * Normalize Vietnamese text: remove diacritics, lowercase, keep alphanumeric.
 * Memoizable — pure function, same input → same output.
 */
const normalizeText = (text: string): string => {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim();
};

/**
 * Extract acronym from a string (up to 5 chars).
 * - Single word: first 4 chars uppercase
 * - Multiple words: first letter of each word, up to 5 chars
 * 
 * Examples: "Kho Tổng" → "KT", "Hồ Chí Minh" → "HCM", "Warehouse" → "WARE"
 */
const getAcronym = (text: string, maxLen = 5): string => {
  const cleaned = normalizeText(text);
  if (!cleaned) return 'WH';

  const words = cleaned.split(/\s+/).filter(Boolean);

  if (words.length === 1) {
    return words[0].substring(0, maxLen).toUpperCase();
  }

  // Multiple words: use first letter of each word
  const acronym = words.map((w) => w[0]).join('').toUpperCase();
  if (acronym.length >= 2) {
    return acronym.substring(0, maxLen);
  }

  return words[0].substring(0, maxLen).toUpperCase();
};

/**
 * Generate a random 3-digit number (100-999).
 */
export const randomDigits = (): string => {
  return String(Math.floor(100 + Math.random() * 900));
};

/**
 * Generate a warehouse code from name and province.
 * Format: WH-{PROVINCE_ACRONYM}-{NAME_ACRONYM}-{3_DIGITS}
 * 
 * This is a pure function (idempotent for same inputs, but includes random suffix).
 * For truly deterministic output (e.g. editing), pass an optional fixedSuffix.
 */
export const generateWarehouseCode = (name: string, province: string, fixedSuffix?: string): string => {
  const provinceCode = getAcronym(province, 4) || 'XX';
  const nameCode = getAcronym(name, 5) || 'WH';
  const suffix = fixedSuffix || randomDigits();
  return `WH-${provinceCode}-${nameCode}-${suffix}`;
};

/**
 * Extract trailing digits from a warehouse code.
 * Example: "WH-HN2-K1HN-374" -> "374"
 */
export const extractCodeSuffix = (existingCode: string): string | undefined => {
  const match = existingCode.match(/(\d+)$/);
  return match ? match[1] : undefined;
};

/**
 * Regenerate just the random suffix part of an existing code.
 * Use this when user clicks "Regenerate" on an auto-generated code.
 */
export const regenerateCodeSuffix = (existingCode: string): string => {
  // Extract the prefix part (WH-XXX-XXX-) and replace suffix
  const match = existingCode.match(/^(WH-[A-Z0-9]+-[A-Z0-9]+-)\d+$/);
  if (match) {
    return match[1] + randomDigits();
  }
  // If code doesn't match expected format, generate fresh
  return existingCode;
};

/**
 * Check if a warehouse code was auto-generated (matches our format).
 */
export const isAutoGeneratedCode = (code: string): boolean => {
  return /^WH-[A-Z0-9]{1,4}-[A-Z0-9]{1,5}-\d{3}$/.test(code);
};